### ISSUE TITLE
FSM was the main pillar for Windows TAPI integration

### ISSUE THREAD

**Issue by aegonzalez** [mpusz/fsm_variant#1]
Hi,
I want to thank you and the original authors for providing this FSM. It eased the work of pairing events and states for the application. 
It was a pleasure to write with this technique of variants. Thank you!
A

**Comment by mpusz** [comment]
Hi,

I am really glad you liked it. Please see my talk at CppCon on that subject:
https://github.com/CppCon/CppCon2018/blob/master/Presentations/effective_replacement_of_dynamic_polymorphism_with_stdvariant/effective_replacement_of_dynamic_polymorphism_with_stdvariant__mateusz_pusz__cppcon_2018.pdf

Best

Mat

**Comment by mpusz** [comment]
Hi,

I updated the repo with the latest version. Please note that I renamed the repo to fsm-variant.

Best

Mat
