### ISSUE TITLE
fsm.h is missing include header <utility> for std::move

### ISSUE THREAD

**Issue by bobwilmes** [mpusz/fsm_variant#2]
Wow - I absolutely loved your example and the CPPcon18 Powerpoint on FSM's
Really - fantastic work.
Thanks for opening my eyes on using this to implement a FSM.

Do you have any ideas about adding a timer event if a state transition does not occur
within a period of time ?

According to www.cplusplus.com/reference/utility/move, the include file:
#include <utility>

is missing from the file:     fsm-variant/src/include/mp/fsm.h

**Comment by mpusz** [comment]
Hi,

I am happy that you liked it and found it useful :-)

Regarding the timer event, there is nothing special about it. It is just a regular event. You can start a timer on_enter() to a new state and the timer should generate an event to this state when a timeout occurs. Does this work for you?

Thanks for pointing out a missing header. Did you find it by having problems in compiling it on any C++ compiler?

**Comment by kuzkry** [comment]
Btw. `std::forward` is used and it also needs the same header.
The only reason why it works must be due to move semantics used in other std headers which leak `<utility>` out. Obviously, we shouldn't depend on such things.

**Comment by mpusz** [comment]
Done. Thank you!

**Comment by kuzkry** [comment]
Cool! Btw. I can see you've just broken the alphabetical order as v comes after u (86e6cdd5) :smile:
