### ISSUE TITLE
Request updating code

### ISSUE THREAD

**Issue by vincent-hui** [mpusz/fsm_variant#3]
Thank you very much for open sourcing your FSM.
Would you mind updating code in github according to your talk in ACCU 2019? fsm.h in ACCU 2019 is more updated than fsm.h in github
https://youtu.be/JGYxOieiZnY

Thank you

**Comment by mpusz** [comment]
Could you please describe in more detail which part do you miss? During my talk. I provided a few implementations alternative and the implementation in this repo is only one of the possibilities here.

**Comment by vincent-hui** [comment]
Sorry, I misunderstood implementations alternatives as the more updated code.
